

services:
  # 1. PostgreSQL (Transactional DB)
  postgres:
    image: postgres:15-alpine
    container_name: mayur-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mayur_hms_core
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mayur-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mayur_hms_core"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. MongoDB (EMR / Documents)
  mongo:
    image: mongo:6.0
    container_name: mayur-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mayur-net

  # 3. Redis (Cache)
  redis:
    image: redis:7-alpine
    container_name: mayur-redis
    ports:
      - "6379:6379"
    networks:
      - mayur-net

  # 4. Zookeeper (for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: mayur-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - mayur-net

  # 5. Kafka (Message Broker)
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: mayur-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - mayur-net

  # 6. Keycloak (IAM)
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: mayur-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      - mayur-net
    volumes:
      - keycloak_data:/opt/keycloak/data

  # 7. Mailpit (Email Testing)
  mailpit:
    image: axllent/mailpit
    container_name: mayur-mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # UI
    networks:
      - mayur-net

  # 8. Zipkin (Tracing)
  zipkin:
    image: openzipkin/zipkin
    container_name: mayur-zipkin
    ports:
      - "9411:9411"
    networks:
      - mayur-net

networks:
  mayur-net:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  keycloak_data:
