server:
  port: 8082

spring:
  application:
    name: identity-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/raksha-realm
          jwk-set-uri: http://localhost:8081/realms/raksha-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Keycloak Admin Configuration
raksha:
  keycloak:
    server-url: http://localhost:8081
    realm: raksha-realm
    client-id: admin-cli
    client-secret: # To be injected via env var
    grant-type: client_credentials
