server:
  port: 8084

spring:
  application:
    name: emr-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/raksha_emr
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
